"""Test that all models are importable from the top-level package."""

from bioimageflow_server.models import (
    ColumnRefEdge,
    ConnectColumnRefOperation,
    ConnectPositionalOperation,
    CreateNodeOperation,
    DeleteEdgeOperation,
    DeleteNodeOperation,
    ErrorResponse,
    ExecutionRequest,
    ExecutionResult,
    ExecutionStatus,
    GraphState,
    GraphValidationError,
    MoveNodeOperation,
    NodeState,
    NodeStatus,
    OMEROInstance,
    PositionalEdge,
    ProgressInfo,
    RenameNodeOperation,
    SetNodeEnabledOperation,
    Settings,
    UpdateNodeParametersOperation,
    ValidationResult,
    WorkflowCreate,
    WorkflowDeleteResponse,
    WorkflowDraftOperationsRequest,
    WorkflowFile,
    WorkflowInfo,
    WorkflowUpdate,
)


def test_all_models_importable():
    expected = [
        ColumnRefEdge,
        ConnectColumnRefOperation,
        ConnectPositionalOperation,
        CreateNodeOperation,
        DeleteEdgeOperation,
        DeleteNodeOperation,
        ErrorResponse,
        ExecutionRequest,
        ExecutionResult,
        ExecutionStatus,
        GraphState,
        GraphValidationError,
        MoveNodeOperation,
        NodeState,
        NodeStatus,
        OMEROInstance,
        PositionalEdge,
        ProgressInfo,
        RenameNodeOperation,
        SetNodeEnabledOperation,
        Settings,
        UpdateNodeParametersOperation,
        ValidationResult,
        WorkflowCreate,
        WorkflowDeleteResponse,
        WorkflowDraftOperationsRequest,
        WorkflowFile,
        WorkflowInfo,
        WorkflowUpdate,
    ]
    for cls in expected:
        assert hasattr(cls, "model_fields"), f"{cls.__name__} is not a Pydantic model"
