/**
 * Hot-reload E2E
 *
 * Drives the full backend → WebSocket → frontend path:
 *   1. Add a tool from the existing tool store onto the canvas.
 *   2. Subscribe to the WebSocket and listen for a `tool_reload` message.
 *   3. Modify a `*.py` file inside the tool fixture so the backend's
 *      watchdog observer fires.
 *   4. Wait up to 3 s for the `tool_reload` message and the resulting
 *      `updatedBadge` UI mutation.
 *   5. Click the badge to dismiss it.
 *
 * This test edits a tool source file, then restores it. The Playwright
 * config points `BIOIMAGEFLOW_HOT_RELOAD_FIXTURE` at an isolated E2E
 * tool-store package generated by the backend test app. If run outside
 * that config, set the env var to an absolute path of a mutable fixture
 * `*.py` file that exports a "Files" tool with `path: str = ''`.
 *
 * macOS FSEvents has a ~300 ms minimum latency. We use a 4.5 s timeout
 * to keep the test robust on CI.
 */

import { test, expect } from '@playwright/test'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'

const API_BASE = `http://127.0.0.1:${process.env.BIOIMAGEFLOW_E2E_BACKEND_PORT ?? '8000'}`

test.describe('hot-reload', () => {
  test('file edit broadcasts tool_reload and surfaces updated badge', async ({ page }) => {
    const fixturePath = process.env.BIOIMAGEFLOW_HOT_RELOAD_FIXTURE
    test.skip(
      !fixturePath || !existsSync(fixturePath),
      "Set BIOIMAGEFLOW_HOT_RELOAD_FIXTURE to an absolute path of a mutable fixture *.py file that exports a Files tool with path: str = ''.",
    )
    const filePath = fixturePath as string
    const original = readFileSync(filePath, 'utf-8')

    await page.goto('/')
    await expect(page.locator('#bioimageflow-app')).toBeVisible()
    const workflowName = `hot_reload_${Date.now()}`
    await page.getByRole('menuitem', { name: 'Workflow', exact: true }).click()
    await page.getByRole('menuitem', { name: 'New', exact: true }).click()
    await page.getByTestId('workflow-display-name-input').fill(workflowName)
    await page.getByTestId('workflow-dialog-submit').click()
    await expect(page.getByTestId('workflow-title')).toContainText(workflowName)

    // Add a Files node so the canvas has at least one node from the fixture.
    await page.locator('.dv-tab').filter({ hasText: 'Tools' }).click()
    await page.locator('[data-testid="tool-search"]').fill('Files')
    const toolRow = page.getByTestId('tool-item-Files')
    await expect(toolRow).toBeVisible({ timeout: 5000 })
    await toolRow.dragTo(page.locator('.vue-flow'), {
      targetPosition: { x: 260, y: 180 },
    })
    const node = page.locator('.vue-flow__node').first()
    await expect(node).toBeVisible({ timeout: 3000 })

    // Register the listener and wait for the backend to accept its socket
    // before editing the fixture. Otherwise Firefox can trigger the file
    // event before the page.evaluate call has established its connection.
    await page.evaluate(async () => {
      type HotReloadMessage = { tool_name: string }
      type HotReloadWindow = typeof window & {
        __bioimageflowHotReloadMessage?: Promise<HotReloadMessage>
        __bioimageflowHotReloadSocket?: WebSocket
      }
      const state = window as HotReloadWindow
      const socket = new WebSocket(
        (location.protocol === 'https:' ? 'wss://' : 'ws://')
        + location.host
        + '/ws',
      )
      state.__bioimageflowHotReloadSocket = socket

      state.__bioimageflowHotReloadMessage = new Promise<HotReloadMessage>((resolve, reject) => {
        let timeout: number | undefined
        socket.addEventListener('open', () => {
          timeout = window.setTimeout(() => {
            socket.close()
            reject(new Error('Did not receive tool_reload within timeout.'))
          }, 4500)
        }, { once: true })
        socket.addEventListener('message', (event) => {
          try {
            const message = JSON.parse(event.data as string)
            if (message.type === 'tool_reload') {
              if (timeout !== undefined)
                window.clearTimeout(timeout)
              socket.close()
              resolve({ tool_name: message.tool_name })
            }
          } catch {
            /* Ignore unrelated non-JSON WebSocket traffic. */
          }
        })
        socket.addEventListener('error', () => {
          if (timeout !== undefined)
            window.clearTimeout(timeout)
          reject(new Error('WebSocket error'))
        }, { once: true })
      })

      await new Promise<void>((resolve, reject) => {
        socket.addEventListener('open', () => resolve(), { once: true })
        socket.addEventListener('error', () => reject(new Error('WebSocket connection failed')), {
          once: true,
        })
      })
    })

    try {
      // Change metadata so ToolHotReloadService's diff emits tool_reload.
      const modified = original.replace(
        "path: str = ''",
        `path: str = 'hot_reload_${Date.now()}'`,
      )
      expect(modified).not.toBe(original)
      writeFileSync(filePath, modified, 'utf-8')

      const result = await page.evaluate(async () => {
        type HotReloadWindow = typeof window & {
          __bioimageflowHotReloadMessage?: Promise<{ tool_name: string }>
        }
        const message = (window as HotReloadWindow).__bioimageflowHotReloadMessage
        if (!message)
          throw new Error('Hot-reload listener was not initialized.')
        return message
      })
      expect(result.tool_name.length).toBeGreaterThan(0)

      // Edit affects every class re-exported from this file (including Files),
      // so the canvas node should pick up the badge.
      await expect(node.locator('.updated-badge')).toBeVisible({ timeout: 3000 })

      // Dismissing clears the badge.
      await node.locator('.updated-badge').click()
      await expect(node.locator('.updated-badge')).toHaveCount(0)
    } finally {
      // Restore the fixture file even if assertions failed.
      writeFileSync(filePath, original, 'utf-8')
      await page.evaluate(() => {
        type HotReloadWindow = typeof window & {
          __bioimageflowHotReloadMessage?: Promise<{ tool_name: string }>
          __bioimageflowHotReloadSocket?: WebSocket
        }
        const state = window as HotReloadWindow
        state.__bioimageflowHotReloadSocket?.close()
        delete state.__bioimageflowHotReloadMessage
        delete state.__bioimageflowHotReloadSocket
      }).catch(() => undefined)
      await page.request.delete(`${API_BASE}/api/v1/workflows/${workflowName}`).catch(() => undefined)
    }
  })
})
