/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tools */
        get: operations["list_tools_api_v1_tools_get"];
        put?: never;
        /** Create Tool */
        post: operations["create_tool_api_v1_tools_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools/packages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Packages */
        get: operations["list_packages_api_v1_tools_packages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools/packages/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh Packages */
        post: operations["refresh_packages_api_v1_tools_packages_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools/{tool_name}/source": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Tool Source */
        get: operations["get_tool_source_api_v1_tools__tool_name__source_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools/{tool_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Tool */
        delete: operations["delete_tool_api_v1_tools__tool_name__delete"];
        options?: never;
        head?: never;
        /** Rename Tool */
        patch: operations["rename_tool_api_v1_tools__tool_name__patch"];
        trace?: never;
    };
    "/api/v1/tools/packages/{package_name}/use": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Use Package Version */
        post: operations["use_package_version_api_v1_tools_packages__package_name__use_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools/packages/{package_name}/install": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Install Package */
        post: operations["install_package_api_v1_tools_packages__package_name__install_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools/packages/{package_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Uninstall Package */
        delete: operations["uninstall_package_api_v1_tools_packages__package_name__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools/environments/{env_name}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Environment */
        post: operations["start_environment_api_v1_tools_environments__env_name__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools/environments/{env_name}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop Environment */
        post: operations["stop_environment_api_v1_tools_environments__env_name__stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dev/seed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Seed Tools
         * @description Register demo tools and packages for E2E testing.
         */
        post: operations["seed_tools_api_v1_dev_seed_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fs/reveal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reveal Path
         * @description Open the given path in the system file browser.
         */
        post: operations["reveal_path_api_v1_fs_reveal_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Validate Graph Endpoint */
        put: operations["validate_graph_endpoint_api_v1_graph_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/graph/nodes/{node_id}/parameters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Node Parameters */
        patch: operations["patch_node_parameters_api_v1_graph_nodes__node_id__parameters_patch"];
        trace?: never;
    };
    "/api/v1/graph/nodes/{node_id}/output_schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolve Node Output Schema
         * @description Return the resolved output column schema for a single node.
         *
         *     The full ``GraphState`` is required because schema resolution may
         *     depend on upstream wiring (e.g. merge tools). Build failures return
         *     ``{resolved: false, columns: {}}`` — input edits frequently produce
         *     transiently invalid graph states.
         */
        post: operations["resolve_node_output_schema_api_v1_graph_nodes__node_id__output_schema_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Datasets */
        get: operations["list_datasets_api_v1_datasets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Datasets */
        post: operations["upload_datasets_api_v1_datasets_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{dataset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Dataset */
        delete: operations["delete_dataset_api_v1_datasets__dataset_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/execution/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Execution */
        post: operations["run_execution_api_v1_execution_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/execution/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop Execution */
        post: operations["stop_execution_api_v1_execution_stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/execution/clear": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clear Execution */
        post: operations["clear_execution_api_v1_execution_clear_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/execution/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Status */
        get: operations["get_status_api_v1_execution_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_datasets_api_v1_datasets_upload_post */
        Body_upload_datasets_api_v1_datasets_upload_post: {
            /** Files */
            files: string[];
        };
        /** ClearRequest */
        ClearRequest: {
            graph: components["schemas"]["GraphState"];
            /** Nodes */
            nodes: string[];
        };
        /**
         * ColumnRefEdge
         * @description Edge that maps a named output column to a named input.
         */
        ColumnRefEdge: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "column_ref";
            /** Id */
            id: string;
            /** Source Node */
            source_node: string;
            /** Target Node */
            target_node: string;
            /** Source Output */
            source_output: string;
            /** Target Input */
            target_input: string;
        };
        /**
         * Dataset
         * @description A stored dataset as returned by `GET /datasets`.
         */
        Dataset: {
            /** Id */
            id: string;
            /** Original Filename */
            original_filename: string;
            /** Path */
            path: string;
            /** Size */
            size: number;
            /** Upload Date */
            upload_date: string;
            /** Content Type */
            content_type?: string | null;
        };
        /**
         * ExecutionRequest
         * @description Request to execute a graph (or a subset of its nodes).
         */
        ExecutionRequest: {
            /** Graph */
            graph: {
                [key: string]: unknown;
            };
            /** Nodes */
            nodes?: string[] | null;
        };
        /**
         * GraphState
         * @description Complete graph state with nodes and edges.
         */
        GraphState: {
            /** Nodes */
            nodes: components["schemas"]["NodeState"][];
            /** Edges */
            edges: (components["schemas"]["ColumnRefEdge"] | components["schemas"]["PositionalEdge"])[];
        };
        /**
         * GraphValidationError
         * @description A single validation error detected in the graph.
         */
        GraphValidationError: {
            /**
             * Type
             * @enum {string}
             */
            type: "cycle_detected" | "type_incompatible" | "parameter_invalid" | "missing_tool" | "missing_connection" | "missing_package" | "invalid_node_id" | "invalid_edge_id" | "source_tool_upstream";
            /** Detail */
            detail: string;
            /** Node */
            node?: string | null;
            /** Edge Id */
            edge_id?: string | null;
            /** Field */
            field?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InputFieldSchema */
        InputFieldSchema: {
            /** Type */
            type: string;
            /** Required */
            required: boolean;
            /**
             * Nullable
             * @default false
             */
            nullable: boolean;
            /**
             * Connectable
             * @enum {string}
             */
            connectable: "never" | "not_by_default" | "by_default";
            /** Default */
            default?: unknown;
            /** Display Name */
            display_name?: string | null;
            /** Description */
            description?: string | null;
            /** Group */
            group?: string | null;
            /** Min */
            min?: number | null;
            /** Max */
            max?: number | null;
            /** Step */
            step?: number | null;
            /** Choices */
            choices?: string[] | null;
            /** Image Spec */
            image_spec?: {
                [key: string]: string[];
            } | null;
        };
        /**
         * NodeOutputSchemaResponse
         * @description Response for ``POST /graph/nodes/{node_id}/output_schema``.
         */
        NodeOutputSchemaResponse: {
            /** Resolved */
            resolved: boolean;
            /** Columns */
            columns: {
                [key: string]: unknown;
            };
        };
        /**
         * NodeState
         * @description A single node in the processing graph.
         */
        NodeState: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Tool Name */
            tool_name: string;
            /** Position */
            position: [
                number,
                number
            ];
            /** Parameters */
            parameters: {
                [key: string]: unknown;
            };
            /**
             * Resources
             * @default {}
             */
            resources: {
                [key: string]: unknown;
            };
            /**
             * Output Templates
             * @default {}
             */
            output_templates: {
                [key: string]: string;
            };
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Collapsed
             * @default false
             */
            collapsed: boolean;
        };
        /**
         * NodeStatus
         * @description Status of a single node after validation or execution.
         */
        NodeStatus: {
            /** Node Id */
            node_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "unexecuted" | "executed" | "out_of_date" | "disabled" | "running" | "failed";
            /** Cached */
            cached: boolean;
            /** Error */
            error?: string | null;
            /** Traceback */
            traceback?: string | null;
        };
        /** PackageInfo */
        PackageInfo: {
            /** Name */
            name: string;
            /**
             * Installed Versions
             * @default []
             */
            installed_versions: string[];
            /**
             * Available Versions
             * @default []
             */
            available_versions: string[];
            /**
             * Tools
             * @default {}
             */
            tools: {
                [key: string]: string[];
            };
            /**
             * Environment Status
             * @default stopped
             */
            environment_status: string;
        };
        /**
         * ParameterPatchRequest
         * @description Body of PATCH /graph/nodes/{id}/parameters — constants only.
         */
        ParameterPatchRequest: {
            /** Parameters */
            parameters: {
                [key: string]: unknown;
            };
        };
        /**
         * PositionalEdge
         * @description Edge that connects nodes by positional index.
         */
        PositionalEdge: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "positional";
            /** Id */
            id: string;
            /** Source Node */
            source_node: string;
            /** Target Node */
            target_node: string;
            /** Positional Index */
            positional_index: number;
        };
        /**
         * RevealRequest
         * @description Request body for the reveal endpoint.
         */
        RevealRequest: {
            /** Path */
            path: string;
        };
        /** ToolCreate */
        ToolCreate: {
            /** Name */
            name: string;
            /**
             * Tool Type
             * @enum {string}
             */
            tool_type: "ProcessingTool" | "DataFrameTool";
        };
        /** ToolMetadata */
        ToolMetadata: {
            /** Name */
            name: string;
            /** Display Name */
            display_name: string;
            /** Package */
            package: string;
            /** Package Version */
            package_version: string;
            /**
             * Tool Type
             * @enum {string}
             */
            tool_type: "ProcessingTool" | "DataFrameTool";
            /**
             * Accepts Upstream
             * @default true
             */
            accepts_upstream: boolean;
            /**
             * Dynamic Outputs
             * @default false
             */
            dynamic_outputs: boolean;
            /**
             * Documentation
             * @default
             */
            documentation: string;
            /**
             * Tags
             * @default []
             */
            tags: string[];
            /**
             * Categories
             * @default []
             */
            categories: string[];
            /**
             * Inputs
             * @default {}
             */
            inputs: {
                [key: string]: components["schemas"]["InputFieldSchema"];
            };
            /**
             * Outputs
             * @default {}
             */
            outputs: {
                [key: string]: unknown;
            };
            /** Environment */
            environment?: {
                [key: string]: unknown;
            } | null;
        };
        /** ToolRename */
        ToolRename: {
            /** New Name */
            new_name: string;
        };
        /**
         * UploadError
         * @description A per-file upload failure, inside `UploadResponse.errors`.
         *
         *     Distinct from the top-level `ErrorResponse` (which is used only for
         *     request-level failures like 400 / 413 / 404).
         */
        UploadError: {
            /** Filename */
            filename: string;
            /** Error */
            error: string;
            /** Detail */
            detail: string;
        };
        /**
         * UploadResponse
         * @description Response body for `POST /datasets/upload`.
         */
        UploadResponse: {
            /**
             * Uploaded
             * @default []
             */
            uploaded: components["schemas"]["UploadedFile"][];
            /**
             * Errors
             * @default []
             */
            errors: components["schemas"]["UploadError"][];
        };
        /**
         * UploadedFile
         * @description A successfully-stored file, inside `UploadResponse.uploaded`.
         */
        UploadedFile: {
            /** Id */
            id: string;
            /** Original Filename */
            original_filename: string;
            /** Path */
            path: string;
            /** Size */
            size: number;
            /** Upload Date */
            upload_date: string;
            /** Content Type */
            content_type?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * ValidationResult
         * @description Result of validating a graph.
         */
        ValidationResult: {
            /** Valid */
            valid: boolean;
            /**
             * Node Statuses
             * @default {}
             */
            node_statuses: {
                [key: string]: components["schemas"]["NodeStatus"];
            };
            /**
             * Errors
             * @default []
             */
            errors: components["schemas"]["GraphValidationError"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type BodyUploadDatasetsApiV1DatasetsUploadPost = components['schemas']['Body_upload_datasets_api_v1_datasets_upload_post'];
export type ClearRequest = components['schemas']['ClearRequest'];
export type ColumnRefEdge = components['schemas']['ColumnRefEdge'];
export type Dataset = components['schemas']['Dataset'];
export type ExecutionRequest = components['schemas']['ExecutionRequest'];
export type GraphState = components['schemas']['GraphState'];
export type GraphValidationError = components['schemas']['GraphValidationError'];
export type HttpValidationError = components['schemas']['HTTPValidationError'];
export type InputFieldSchema = components['schemas']['InputFieldSchema'];
export type NodeOutputSchemaResponse = components['schemas']['NodeOutputSchemaResponse'];
export type NodeState = components['schemas']['NodeState'];
export type NodeStatus = components['schemas']['NodeStatus'];
export type PackageInfo = components['schemas']['PackageInfo'];
export type ParameterPatchRequest = components['schemas']['ParameterPatchRequest'];
export type PositionalEdge = components['schemas']['PositionalEdge'];
export type RevealRequest = components['schemas']['RevealRequest'];
export type ToolCreate = components['schemas']['ToolCreate'];
export type ToolMetadata = components['schemas']['ToolMetadata'];
export type ToolRename = components['schemas']['ToolRename'];
export type UploadError = components['schemas']['UploadError'];
export type UploadResponse = components['schemas']['UploadResponse'];
export type UploadedFile = components['schemas']['UploadedFile'];
export type ValidationError = components['schemas']['ValidationError'];
export type ValidationResult = components['schemas']['ValidationResult'];
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_tools_api_v1_tools_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolMetadata"][];
                };
            };
        };
    };
    create_tool_api_v1_tools_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ToolCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_packages_api_v1_tools_packages_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackageInfo"][];
                };
            };
        };
    };
    refresh_packages_api_v1_tools_packages_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_tool_source_api_v1_tools__tool_name__source_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tool_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_tool_api_v1_tools__tool_name__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tool_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_tool_api_v1_tools__tool_name__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tool_name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ToolRename"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    use_package_version_api_v1_tools_packages__package_name__use_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                package_name: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    [key: string]: string;
                } | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    install_package_api_v1_tools_packages__package_name__install_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                package_name: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    [key: string]: string;
                } | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    uninstall_package_api_v1_tools_packages__package_name__delete: {
        parameters: {
            query?: {
                version?: string | null;
            };
            header?: never;
            path: {
                package_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_environment_api_v1_tools_environments__env_name__start_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                env_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_environment_api_v1_tools_environments__env_name__stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                env_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    seed_tools_api_v1_dev_seed_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
        };
    };
    reveal_path_api_v1_fs_reveal_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevealRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_graph_endpoint_api_v1_graph_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GraphState"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_node_parameters_api_v1_graph_nodes__node_id__parameters_patch: {
        parameters: {
            query?: {
                tool_name?: string | null;
            };
            header?: never;
            path: {
                node_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParameterPatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_node_output_schema_api_v1_graph_nodes__node_id__output_schema_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                node_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GraphState"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeOutputSchemaResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_datasets_api_v1_datasets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dataset"][];
                };
            };
        };
    };
    upload_datasets_api_v1_datasets_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_datasets_api_v1_datasets_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_dataset_api_v1_datasets__dataset_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_execution_api_v1_execution_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExecutionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_execution_api_v1_execution_stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    clear_execution_api_v1_execution_clear_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClearRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_status_api_v1_execution_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
