"""Live workflow draft persistence for agent-visible unsaved state."""

from __future__ import annotations

import hashlib
import json
import os
import sys
import tempfile
import uuid
from collections.abc import Callable
from dataclasses import dataclass
from datetime import UTC, datetime
from functools import partial
from pathlib import Path
from typing import Any

from bioimageflow_server.models.graph import GraphState
from bioimageflow_server.models.validation import NodeStatus, ValidationResult
from bioimageflow_server.models.workflow_draft import (
    DraftWriter,
    WorkflowDraftResponse,
)
from bioimageflow_server.services.agent_workspace_context import (
    PLATFORM_SOURCE_DIR,
    agent_workspace_instructions,
)
from bioimageflow_server.services.graph_validator import validate_graph
from bioimageflow_server.services.graph_worker import run_graph_work
from bioimageflow_server.services.workflow_store import (
    WorkflowStoreService,
    normalize_workflow_draft_identity,
)


_BACKEND_PACKAGE_PARENT = Path(__file__).resolve().parents[2]
_MCP_SERVER_NAME = "bioimageflow"
_CODEX_GENERATED_COMMENT = (
    "# Generated by BioImageFlow. The bioimageflow MCP server entry may be overwritten."
)


def _utc_now() -> str:
    return datetime.now(UTC).isoformat().replace("+00:00", "Z")


def _json_dump_atomic(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_name = tempfile.mkstemp(
        dir=str(path.parent),
        prefix=f".{path.name}.",
        suffix=".tmp",
    )
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            json.dump(payload, handle, indent=2, sort_keys=True)
            handle.write("\n")
        os.replace(tmp_name, path)
    except Exception:
        try:
            os.unlink(tmp_name)
        except FileNotFoundError:
            pass
        raise


def _text_dump_atomic(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_name = tempfile.mkstemp(
        dir=str(path.parent),
        prefix=f".{path.name}.",
        suffix=".tmp",
    )
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(content)
        os.replace(tmp_name, path)
    except Exception:
        try:
            os.unlink(tmp_name)
        except FileNotFoundError:
            pass
        raise


def _write_agent_client_configs(
    workspace_dir: Path,
    *,
    mcp_client_config: dict[str, Any],
) -> tuple[dict[str, str], dict[str, str]]:
    files: dict[str, str] = {}
    errors: dict[str, str] = {}
    writers = {
        "codex": lambda: _write_codex_mcp_config(
            workspace_dir / ".codex" / "config.toml",
            mcp_client_config,
        ),
        "claude_code": lambda: _write_standard_mcp_json(
            workspace_dir / ".mcp.json",
            _standard_mcp_server_config(mcp_client_config),
        ),
        "opencode": lambda: _write_opencode_config(
            workspace_dir / "opencode.json",
            mcp_client_config,
        ),
        "oh_my_pi": lambda: _write_standard_mcp_json(
            workspace_dir / ".omp" / "mcp.json",
            _omp_mcp_server_config(mcp_client_config),
        ),
        "shared_mcp_json": lambda: _write_standard_mcp_json(
            workspace_dir / ".bioimageflow" / "mcp-client-config.json",
            _standard_mcp_server_config(mcp_client_config),
        ),
    }
    for name, writer in writers.items():
        try:
            files[name] = str(writer())
        except Exception as exc:  # noqa: BLE001 - optional agent configs must not block draft reads
            errors[name] = str(exc)
    return files, errors


def _standard_mcp_server_config(mcp_client_config: dict[str, Any]) -> dict[str, Any]:
    return {
        "command": mcp_client_config["command"],
        "args": list(mcp_client_config.get("args") or []),
        "cwd": mcp_client_config["cwd"],
        "env": dict(mcp_client_config.get("env") or {}),
    }


def _omp_mcp_server_config(mcp_client_config: dict[str, Any]) -> dict[str, Any]:
    return {
        **_standard_mcp_server_config(mcp_client_config),
        "type": "stdio",
        "enabled": True,
        "timeout": 30000,
    }


def _write_standard_mcp_json(path: Path, server_config: dict[str, Any]) -> Path:
    data = _read_json_object(path)
    servers = data.get("mcpServers")
    if servers is None:
        servers = {}
        data["mcpServers"] = servers
    if not isinstance(servers, dict):
        raise ValueError(f"{path} has non-object mcpServers")
    servers[_MCP_SERVER_NAME] = server_config
    _json_dump_atomic(path, data)
    return path


def _write_opencode_config(path: Path, mcp_client_config: dict[str, Any]) -> Path:
    data = _read_json_object(path)
    data.setdefault("$schema", "https://opencode.ai/config.json")
    mcp = data.get("mcp")
    if mcp is None:
        mcp = {}
        data["mcp"] = mcp
    if not isinstance(mcp, dict):
        raise ValueError(f"{path} has non-object mcp")
    mcp[_MCP_SERVER_NAME] = {
        "type": "local",
        "command": [
            mcp_client_config["command"],
            *list(mcp_client_config.get("args") or []),
        ],
        "cwd": mcp_client_config["cwd"],
        "environment": dict(mcp_client_config.get("env") or {}),
        "enabled": True,
        "timeout": 30000,
    }
    _json_dump_atomic(path, data)
    return path


def _read_json_object(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError(f"{path} must contain a JSON object")
    return data


def _write_codex_mcp_config(path: Path, mcp_client_config: dict[str, Any]) -> Path:
    existing = path.read_text(encoding="utf-8") if path.exists() else ""
    existing = "\n".join(
        line for line in existing.splitlines() if line.strip() != _CODEX_GENERATED_COMMENT
    )
    cleaned = _remove_toml_tables(
        existing,
        {"mcp_servers.bioimageflow", "mcp_servers.bioimageflow.env"},
    )
    block = _codex_mcp_toml_block(mcp_client_config)
    separator = "\n\n" if cleaned.strip() else ""
    content = f"{cleaned.rstrip()}{separator}{block}"
    _text_dump_atomic(path, content)
    return path


def _remove_toml_tables(content: str, table_names: set[str]) -> str:
    lines = content.splitlines()
    kept: list[str] = []
    skipping = False
    for line in lines:
        stripped = line.strip()
        if stripped.startswith("[") and stripped.endswith("]"):
            table = stripped.strip("[]").strip()
            skipping = table in table_names
        if not skipping:
            kept.append(line)
    return "\n".join(kept)


def _codex_mcp_toml_block(mcp_client_config: dict[str, Any]) -> str:
    args = list(mcp_client_config.get("args") or [])
    env = dict(mcp_client_config.get("env") or {})
    lines = [
        _CODEX_GENERATED_COMMENT,
        "[mcp_servers.bioimageflow]",
        f"command = {_toml_string(mcp_client_config['command'])}",
        f"args = {_toml_string_array(args)}",
        f"cwd = {_toml_string(mcp_client_config['cwd'])}",
        "startup_timeout_sec = 30",
        "",
        "[mcp_servers.bioimageflow.env]",
    ]
    lines.extend(f"{key} = {_toml_string(value)}" for key, value in sorted(env.items()))
    return "\n".join(lines) + "\n"


def _toml_string(value: Any) -> str:
    return json.dumps(str(value))


def _toml_string_array(values: list[Any]) -> str:
    return "[" + ", ".join(_toml_string(value) for value in values) + "]"


class WorkflowDraftRevisionConflict(ValueError):
    """Raised when a draft write uses a stale expected revision."""

    def __init__(
        self,
        *,
        expected_revision: int,
        current: WorkflowDraftResponse,
    ) -> None:
        self.expected_revision = expected_revision
        self.current = current
        super().__init__(
            f"Draft revision conflict: expected {expected_revision}, "
            f"current is {current.draft_revision}"
        )


class _SavedWorkflowChanged(RuntimeError):
    """Signal that validation must restart against a newer saved artifact."""


@dataclass(frozen=True)
class WorkflowDraftAuthoritySnapshot:
    """One draft plus the durable workflow context that authorized its read."""

    draft: WorkflowDraftResponse
    identity_generation: int
    storage_path: Path


@dataclass(frozen=True)
class _DraftWritePreparation:
    store: WorkflowStoreService
    workflow_id: str
    expected_revision: int
    identity_generation: int
    current: WorkflowDraftResponse
    graph: GraphState
    saved_revision: str
    dirty_against_saved: bool


class WorkflowDraftService:
    """Manage live drafts under workflow-local ``.bioimageflow`` folders."""

    def __init__(
        self,
        workflow_store_provider: Callable[[], WorkflowStoreService],
        *,
        dev_mode_provider: Callable[[], bool] | None = None,
        settings_provider: Callable[[], Any | None] | None = None,
        server_boot_id: str | None = None,
    ) -> None:
        self._workflow_store_provider = workflow_store_provider
        self._dev_mode_provider = dev_mode_provider or (lambda: True)
        self._settings_provider = settings_provider or (lambda: None)
        self.server_boot_id = server_boot_id or uuid.uuid4().hex

    def get_draft(
        self,
        workflow_id: str,
        *,
        api_base_url: str | None = None,
    ) -> WorkflowDraftResponse:
        store = self._store()
        draft = self._read_validated_snapshot(store, workflow_id)
        self.write_agent_context(
            store,
            workflow_id=workflow_id,
            draft=draft,
            api_base_url=api_base_url,
        )
        return draft

    async def get_draft_async(
        self,
        workflow_id: str,
        *,
        api_base_url: str | None = None,
    ) -> WorkflowDraftResponse:
        """Read a draft without running filesystem or validation work on the event loop."""

        return await run_graph_work(
            partial(
                self.get_draft,
                workflow_id,
                api_base_url=api_base_url,
            )
        )

    def get_draft_snapshot(self, workflow_id: str) -> WorkflowDraftResponse:
        """Return the latest draft without updating agent workspace context."""

        store = self._store()
        return self._read_validated_authority_snapshot(store, workflow_id).draft

    async def get_draft_snapshot_async(
        self,
        workflow_id: str,
    ) -> WorkflowDraftResponse:
        """Return a draft snapshot without blocking the event loop."""

        return await run_graph_work(partial(self.get_draft_snapshot, workflow_id))

    def get_draft_authority(
        self,
        workflow_id: str,
    ) -> WorkflowDraftAuthoritySnapshot:
        """Return a validated draft and its atomic identity/storage authority."""

        store = self._store()
        return self._read_validated_authority_snapshot(store, workflow_id)

    async def get_draft_authority_async(
        self,
        workflow_id: str,
    ) -> WorkflowDraftAuthoritySnapshot:
        """Read draft authority through the bounded graph worker."""

        return await run_graph_work(partial(self.get_draft_authority, workflow_id))

    def get_draft_authority_snapshot(
        self,
        workflow_id: str,
    ) -> WorkflowDraftResponse:
        """Read current draft authority without compiling or updating agent context.

        Callers may already hold the same workflow mutation lock when several
        authority fields must be checked at one linearization point.
        """

        store = self._store()
        with store.workflow_mutation(workflow_id):
            return self._read_current_for_mutation_locked(store, workflow_id)

    def put_draft(
        self,
        workflow_id: str,
        *,
        graph: GraphState,
        expected_revision: int,
        updated_by: DraftWriter = "frontend",
        should_validate: bool = True,
        api_base_url: str | None = None,
    ) -> WorkflowDraftResponse:
        graph = graph.model_copy(deep=True)
        while True:
            prepared = self._prepare_draft_write(
                workflow_id,
                graph=graph,
                expected_revision=expected_revision,
            )
            try:
                validation = (
                    self._validate(prepared.store, workflow_id, graph)
                    if should_validate
                    else self._default_validation(graph)
                )
            except Exception:
                try:
                    self._ensure_draft_preparation_current(prepared)
                except _SavedWorkflowChanged:
                    continue
                raise
            try:
                return self._commit_draft_write(
                    prepared,
                    validation=validation,
                    updated_by=updated_by,
                    api_base_url=api_base_url,
                )
            except _SavedWorkflowChanged:
                continue

    async def put_draft_async(
        self,
        workflow_id: str,
        *,
        graph: GraphState,
        expected_revision: int,
        updated_by: DraftWriter = "frontend",
        should_validate: bool = True,
        api_base_url: str | None = None,
    ) -> WorkflowDraftResponse:
        """Validate and commit a draft through the bounded graph worker."""

        graph = graph.model_copy(deep=True)
        return await run_graph_work(
            partial(
                self.put_draft,
                workflow_id,
                graph=graph,
                expected_revision=expected_revision,
                updated_by=updated_by,
                should_validate=should_validate,
                api_base_url=api_base_url,
            )
        )

    def reset_draft_to_saved(
        self,
        workflow_id: str,
        *,
        expected_revision: int,
        updated_by: DraftWriter = "frontend",
        api_base_url: str | None = None,
    ) -> WorkflowDraftResponse:
        """CAS-replace the accepted draft with the current saved graph."""

        while True:
            prepared = self._prepare_reset_to_saved(
                workflow_id,
                expected_revision=expected_revision,
            )
            try:
                validation = self._validate(
                    prepared.store,
                    workflow_id,
                    prepared.graph,
                )
            except Exception:
                try:
                    self._ensure_draft_preparation_current(prepared)
                except _SavedWorkflowChanged:
                    continue
                raise
            try:
                return self._commit_draft_write(
                    prepared,
                    validation=validation,
                    updated_by=updated_by,
                    api_base_url=api_base_url,
                )
            except _SavedWorkflowChanged:
                continue

    async def reset_draft_to_saved_async(
        self,
        workflow_id: str,
        *,
        expected_revision: int,
        updated_by: DraftWriter = "frontend",
        api_base_url: str | None = None,
    ) -> WorkflowDraftResponse:
        """Reset a draft through the bounded graph worker."""

        return await run_graph_work(
            partial(
                self.reset_draft_to_saved,
                workflow_id,
                expected_revision=expected_revision,
                updated_by=updated_by,
                api_base_url=api_base_url,
            )
        )

    def write_agent_context(
        self,
        store: WorkflowStoreService,
        *,
        workflow_id: str,
        draft: WorkflowDraftResponse,
        api_base_url: str | None = None,
    ) -> None:
        workspace_meta = store.workspace_dir / ".bioimageflow"
        workspace_meta.mkdir(parents=True, exist_ok=True)
        api_url = (api_base_url or "http://127.0.0.1:8000/api/v1").rstrip("/")
        state_path = workspace_meta / "agent-state.json"
        pythonpath = str(_BACKEND_PACKAGE_PARENT)
        if existing_pythonpath := os.environ.get("PYTHONPATH"):
            pythonpath = os.pathsep.join((pythonpath, existing_pythonpath))
        mcp_client_config = {
            "command": sys.executable,
            "args": ["-m", "bioimageflow_server.agent_mcp"],
            "cwd": str(store.workspace_dir),
            "env": {
                "BIOIMAGEFLOW_AGENT_STATE": str(state_path),
                "PYTHONPATH": pythonpath,
            },
        }
        client_config_files, client_config_errors = _write_agent_client_configs(
            store.workspace_dir,
            mcp_client_config=mcp_client_config,
        )
        context = {
            "agent_state_version": 2,
            "mcp_contract_version": 2,
            "generated_at": _utc_now(),
            "server_boot_id": self.server_boot_id,
            "server_pid": os.getpid(),
            "api_base_url": api_url,
            "health_url": f"{api_url}/health",
            "active_workflow_id": workflow_id,
            "current_draft_revision": draft.draft_revision,
            "workspace_path": str(store.workspace_dir),
            "workflows_root": str(store.root_dir),
            "active_draft_path": str(self._draft_path(store, workflow_id)),
            "agent_state_path": str(state_path),
            "mcp_server_command": f"{sys.executable} -m bioimageflow_server.agent_mcp",
            "mcp_client_config": mcp_client_config,
            "agent_client_config_files": client_config_files,
            "recommended_commands": [
                "MCP get_bioimageflow_capabilities {}",
                "MCP get_workspace_context {}",
                "MCP list_workflows {}",
                "MCP describe_workflow {}",
                "MCP list_tools {}",
                'MCP describe_bioimageflow_tool {"tool_name":"<tool name>"}',
                'MCP create_workflow {"workflow_id":"<workflow id>","display_name":"<display name>","set_active":true}',
                'MCP duplicate_workflow {"source_workflow_id":"<workflow id>","new_workflow_id":"<new workflow id>","set_active":true}',
                'MCP set_active_workflow {"workflow_id":"<workflow id>"}',
                'MCP create_node {"node_id":"<id>","tool_name":"<tool name>","name":"<display name>","position":[0,0],"parameters":{}}',
                'MCP connect_nodes {"source_node":"<id>","source_output":"<output>","target_node":"<id>","target_input":"<input>"}',
                'MCP update_node_parameters {"node_id":"<id>","parameters":{}}',
                'MCP apply_workflow_operations {"operations":[{"type":"create_node","node_id":"<id>","tool_name":"<tool name>","name":"<display name>","position":[0,0],"parameters":{}}]}',
                "MCP validate_workflow {}",
                'MCP run_workflow {"nodes":["<optional node id>"]}',
                "MCP get_execution_status {}",
            ],
        }
        if client_config_errors:
            context["agent_client_config_errors"] = client_config_errors
        _json_dump_atomic(state_path, context)
        source_reference = workspace_meta / PLATFORM_SOURCE_DIR
        (store.workspace_dir / "AGENTS.md").write_text(
            agent_workspace_instructions(
                source_path=source_reference if source_reference.exists() else None
            ),
            encoding="utf-8",
        )

    def _store(self) -> WorkflowStoreService:
        return self._workflow_store_provider()

    def _draft_path(self, store: WorkflowStoreService, workflow_id: str) -> Path:
        return store.workflow_dir(workflow_id) / ".bioimageflow" / "draft.json"

    def _read_existing_draft_locked(
        self,
        store: WorkflowStoreService,
        workflow_id: str,
    ) -> WorkflowDraftResponse | None:
        store.ensure_workflow_mutations_available()
        raw = normalize_workflow_draft_identity(
            store.workflow_dir(workflow_id),
            workflow_id,
        )
        return WorkflowDraftResponse.model_validate(raw) if raw is not None else None

    def _read_current_for_mutation_locked(
        self,
        store: WorkflowStoreService,
        workflow_id: str,
    ) -> WorkflowDraftResponse:
        existing = self._read_existing_draft_locked(store, workflow_id)
        if existing is not None:
            return existing
        return self._synthesized_draft(
            store,
            workflow_id,
            validation=self._default_validation(
                store.get_workflow(workflow_id).graph,
            ),
        )

    def _read_validated_snapshot(
        self,
        store: WorkflowStoreService,
        workflow_id: str,
    ) -> WorkflowDraftResponse:
        return self._read_validated_authority_snapshot(store, workflow_id).draft

    def _read_validated_authority_snapshot(
        self,
        store: WorkflowStoreService,
        workflow_id: str,
    ) -> WorkflowDraftAuthoritySnapshot:
        """Read one coherent draft without validating under its mutation lock."""

        while True:
            with store.workflow_mutation(workflow_id):
                identity_generation = store.workflow_generation(workflow_id)
                storage_path = store.get_storage_path(workflow_id)
                existing = self._read_existing_draft_locked(store, workflow_id)
                if existing is not None:
                    return WorkflowDraftAuthoritySnapshot(
                        draft=existing,
                        identity_generation=identity_generation,
                        storage_path=storage_path,
                    )
                saved_revision = self._saved_revision(store, workflow_id)
                synthesized = self._synthesized_draft(
                    store,
                    workflow_id,
                    validation=self._default_validation(
                        store.get_workflow(workflow_id).graph,
                    ),
                )

            validation = self._validate(store, workflow_id, synthesized.graph)

            with store.workflow_mutation(workflow_id):
                store.ensure_workflow_generation(
                    workflow_id,
                    identity_generation,
                )
                existing = self._read_existing_draft_locked(store, workflow_id)
                if existing is not None:
                    return WorkflowDraftAuthoritySnapshot(
                        draft=existing,
                        identity_generation=identity_generation,
                        storage_path=store.get_storage_path(workflow_id),
                    )
                if (
                    self._saved_revision(store, workflow_id) != saved_revision
                    or store.get_storage_path(workflow_id) != storage_path
                ):
                    continue
                return WorkflowDraftAuthoritySnapshot(
                    draft=synthesized.model_copy(update={"validation": validation}),
                    identity_generation=identity_generation,
                    storage_path=storage_path,
                )

    def _prepare_draft_write(
        self,
        workflow_id: str,
        *,
        graph: GraphState,
        expected_revision: int,
    ) -> _DraftWritePreparation:
        store = self._store()
        with store.workflow_mutation(workflow_id):
            current = self._read_current_for_mutation_locked(store, workflow_id)
            self._ensure_expected_revision(current, expected_revision)
            return _DraftWritePreparation(
                store=store,
                workflow_id=workflow_id,
                expected_revision=expected_revision,
                identity_generation=store.workflow_generation(workflow_id),
                current=current,
                graph=graph,
                saved_revision=self._saved_revision(store, workflow_id),
                dirty_against_saved=self._graph_differs_from_saved(
                    store,
                    workflow_id,
                    graph,
                ),
            )

    def _prepare_reset_to_saved(
        self,
        workflow_id: str,
        *,
        expected_revision: int,
    ) -> _DraftWritePreparation:
        store = self._store()
        with store.workflow_mutation(workflow_id):
            current = self._read_current_for_mutation_locked(store, workflow_id)
            self._ensure_expected_revision(current, expected_revision)
            saved = store.get_workflow(workflow_id).graph
            return _DraftWritePreparation(
                store=store,
                workflow_id=workflow_id,
                expected_revision=expected_revision,
                identity_generation=store.workflow_generation(workflow_id),
                current=current,
                graph=saved,
                saved_revision=self._saved_revision(store, workflow_id),
                dirty_against_saved=False,
            )

    def _commit_draft_write(
        self,
        prepared: _DraftWritePreparation,
        *,
        validation: ValidationResult,
        updated_by: DraftWriter,
        api_base_url: str | None,
    ) -> WorkflowDraftResponse:
        store = prepared.store
        workflow_id = prepared.workflow_id
        with store.workflow_mutation(workflow_id):
            current = self._recheck_draft_preparation_locked(prepared)

            draft = WorkflowDraftResponse(
                workflow_id=workflow_id,
                base_saved_revision=(
                    current.base_saved_revision
                    if prepared.dirty_against_saved
                    else prepared.saved_revision
                ),
                draft_revision=current.draft_revision + 1,
                updated_at=_utc_now(),
                updated_by=updated_by,
                dirty_against_saved=prepared.dirty_against_saved,
                graph=prepared.graph,
                validation=validation,
            )
            _json_dump_atomic(
                self._draft_path(store, workflow_id),
                draft.model_dump(mode="json"),
            )
            self.write_agent_context(
                store,
                workflow_id=workflow_id,
                draft=draft,
                api_base_url=api_base_url,
            )
            return draft

    def _ensure_draft_preparation_current(
        self,
        prepared: _DraftWritePreparation,
    ) -> WorkflowDraftResponse:
        with prepared.store.workflow_mutation(prepared.workflow_id):
            return self._recheck_draft_preparation_locked(prepared)

    def _recheck_draft_preparation_locked(
        self,
        prepared: _DraftWritePreparation,
    ) -> WorkflowDraftResponse:
        store = prepared.store
        workflow_id = prepared.workflow_id
        store.ensure_workflow_generation(
            workflow_id,
            prepared.identity_generation,
        )
        current = self._read_current_for_mutation_locked(store, workflow_id)
        self._ensure_expected_revision(current, prepared.expected_revision)
        if self._saved_revision(store, workflow_id) != prepared.saved_revision:
            raise _SavedWorkflowChanged
        return current

    @staticmethod
    def _ensure_expected_revision(
        current: WorkflowDraftResponse,
        expected_revision: int,
    ) -> None:
        if expected_revision != current.draft_revision:
            raise WorkflowDraftRevisionConflict(
                expected_revision=expected_revision,
                current=current,
            )

    def _synthesized_draft(
        self,
        store: WorkflowStoreService,
        workflow_id: str,
        *,
        validation: ValidationResult,
    ) -> WorkflowDraftResponse:
        workflow = store.get_workflow(workflow_id)
        return WorkflowDraftResponse(
            workflow_id=workflow_id,
            base_saved_revision=self._saved_revision(store, workflow_id),
            draft_revision=0,
            updated_at=workflow.info.last_modified,
            updated_by="system",
            dirty_against_saved=False,
            graph=workflow.graph,
            validation=validation,
        )

    def _saved_revision(self, store: WorkflowStoreService, workflow_id: str) -> str:
        path = store.workflow_dir(workflow_id) / "workflow.json"
        digest = hashlib.sha256(path.read_bytes()).hexdigest()
        return f"sha256:{digest}"

    def _validate(
        self,
        store: WorkflowStoreService,
        workflow_id: str,
        graph: GraphState,
    ) -> ValidationResult:
        return validate_graph(
            graph,
            store.tool_registry,
            storage_path=store.get_storage_path(workflow_id),
            dev_mode=self._dev_mode_provider(),
            settings=self._settings_provider(),
        )

    @staticmethod
    def _default_validation(graph: GraphState) -> ValidationResult:
        return ValidationResult(
            valid=True,
            node_statuses={
                node.id: NodeStatus(
                    node_id=node.id,
                    status="unexecuted",
                    cached=False,
                )
                for node in graph.nodes
            },
            errors=[],
        )

    def _graph_differs_from_saved(
        self,
        store: WorkflowStoreService,
        workflow_id: str,
        graph: GraphState,
    ) -> bool:
        try:
            saved = store.get_workflow(workflow_id).graph
        except FileNotFoundError:
            return True
        return saved.model_dump(mode="json") != graph.model_dump(mode="json")
